export const OPEN_MODAL = 'OPEN_MODAL';
export const SCHEDULE_MESSAGE = 'SCHEDULE_MESSAGE';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const WARNING_DELETE_MESSAGE = 'WARNING_DELETE_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
